### ISSUE TITLE
User / pass incorrect connecting

### ISSUE THREAD

**Issue by rbuffi** [theherk/pinkopy#32]
Hello,

We are trying to connect to the commvault api but we get the following error:

requests.exceptions.HTTPError: Commvault user or pass incorrect

In the commvault weblog we see the following.
Maybe you can help me out.

15956 144   11/15 15:06:49 ### ### CVWebService.CVWebSvc.Login --- Exception Message [JSON root object has multiple properties. The root object must have a single property in order to create a valid XML document. Consider specifing a DeserializeRootElementName.]
15956 144   11/15 15:06:49 ### ### CVWebService.CVWebSvc.Login --- Exception Source [Newtonsoft.Json]
15956 144   11/15 15:06:49 ### ### CVWebService.CVWebSvc.Login --- Exception InnerException []
15956 144   11/15 15:06:49 ### ### CVWebService.CVWebSvc.Login --- Exception StackTrace [   at Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeNode(JsonReader reader, IXmlDocument document, XmlNamespaceManager manager, IXmlNode currentNode)
   at Newtonsoft.Json.Converters.XmlNodeConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeXNode(String value, String deserializeRootElementName, Boolean writeArrayAttribute)
   at CVWebService.CVWebSvc.ReadXml(String function, Message reqMsg, Object destinationObj, Boolean asDataContractObject, Boolean traceRequest)
   at CVWebService.CVWebSvc.MessageToObject[T](String function, Message reqMsg, Boolean traceRequest)
   at CVWebService.CVWebSvc.Login(Message reqMsg)]

**Comment by theherk** [comment]
Sorry, I had forgotten to reply to this. I'm not sure what is causing your issue. It could have to do with changes that have taken place in the Commvault API. It has changed a few times, sometimes without notice and sometimes without documentation.

What version of Commvault / Simpana are you using? What does a login request that you know works look like?
